//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Курсовой.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Ариэль {
            get {
                return ResourceManager.GetString("Ариэль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Венера
        ///Вторая планета от солнца
        ///И прочая очень интересная информация
        ///новая полезная информация.
        /// </summary>
        internal static string Венера {
            get {
                return ResourceManager.GetString("Венера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Ганимед {
            get {
                return ResourceManager.GetString("Ганимед", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Деймос {
            get {
                return ResourceManager.GetString("Деймос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Европа {
            get {
                return ResourceManager.GetString("Европа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Земля́ — третья по удалённости от Солнца планета Солнечной системы. Самая плотная, пятая по диаметру и массе среди всех планет Солнечной системы и крупнейшая среди планет земной группы
        ///Орбитальные характеристики
        ///Перигелий 	
        ///147 098 290 км
        ///0,98329134 а.е.
        ///Афелий
        ///152 098 232 км
        ///1,01671388 а.е.
        ///Большая полуось (a) 	
        ///149 598 261 км
        ///1,00000261 а.е.
        ///Эксцентриситет орбиты (e)
        ///0,01671123
        ///Сидерический период обращения
        ///365,256363004 дней
        ///365 сут 6 ч 9 мин 10 с
        ///Орбитальная скорость (v) 	
        ///29,783 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Земля {
            get {
                return ResourceManager.GetString("Земля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Ио {
            get {
                return ResourceManager.GetString("Ио", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Каллисто {
            get {
                return ResourceManager.GetString("Каллисто", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Луна {
            get {
                return ResourceManager.GetString("Луна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Марс {
            get {
                return ResourceManager.GetString("Марс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меркурий
        ///Первая планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Меркурий {
            get {
                return ResourceManager.GetString("Меркурий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Миранда {
            get {
                return ResourceManager.GetString("Миранда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Нептун {
            get {
                return ResourceManager.GetString("Нептун", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Оберон {
            get {
                return ResourceManager.GetString("Оберон", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Сатурн {
            get {
                return ResourceManager.GetString("Сатурн", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Титан {
            get {
                return ResourceManager.GetString("Титан", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Титания {
            get {
                return ResourceManager.GetString("Титания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Тритон {
            get {
                return ResourceManager.GetString("Тритон", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Умбриэль {
            get {
                return ResourceManager.GetString("Умбриэль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Уран {
            get {
                return ResourceManager.GetString("Уран", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Фобос {
            get {
                return ResourceManager.GetString("Фобос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля
        ///Третья планета от солнца
        ///И прочая очень интересная информация.
        /// </summary>
        internal static string Юпитер {
            get {
                return ResourceManager.GetString("Юпитер", resourceCulture);
            }
        }
    }
}
